<a href="https://colab.research.google.com/github/abubakarshahid439/ABUBAKAR.flyrank-ml-internship/blob/main/work/notebooks/w07_action_playbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-10 — Content Action Playbook

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/abubakarshahid439/ABUBAKAR.flyrank-ml-internship/blob/main/work/notebooks/w07_action_playbook.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Ranked actions + reason codes

Ranked Content Actions (Observed & Directional)

Update high-impression, low-CTR content
Reason: Observed that pages with high impressions but low CTR may have weak titles or meta descriptions.
Action: Improve headlines and meta descriptions.
Refresh outdated content with declining traffic
Reason: Measured traffic drop suggests content may be outdated.
Action: Update statistics, keywords, and examples.
Expand high-performing content
Reason: Pages with high engagement show strong user interest.
Action: Add more depth, FAQs, and internal links.
Fix low-engagement content
Reason: Low scroll rate and engagement indicate weak content quality.
Action: Improve readability and structure.
Remove or merge underperforming pages
Reason: Very low impressions and engagement suggest low value.
Action: Merge with related content or delete

In [7]:
import pandas as pd

# Example dataset (replace with your real data)
data = {
    "content_id": ["A", "B", "C", "D", "E"],
    "impressions": [10000, 5000, 8000, 2000, 500],
    "ctr": [0.01, 0.05, 0.02, 0.03, 0.005],
    "engagement": [0.2, 0.6, 0.5, 0.3, 0.1]
}

df = pd.DataFrame(data)

# Ranking logic
df["priority_score"] = df["impressions"] * (1 - df["ctr"])

df = df.sort_values(by="priority_score", ascending=False)

df.head()

  content_id  impressions    ctr  engagement  priority_score
0          A        10000  0.010         0.2          9900.0
2          C         8000  0.020         0.5          7840.0
1          B         5000  0.050         0.6          4750.0
3          D         2000  0.030         0.3          1940.0
4          E          500  0.005         0.1           497.5

## 2. Intended use and limits

Intended Use

This system supports content teams and SEO analysts in prioritizing updates.
It provides directional insights, not final decisions.
Helps identify where to improve content performance.

Limits

Results depend on historical data quality.
Does not guarantee traffic growth.
Cannot understand content quality like a human.
Not valid for completely new content with no data.

In [8]:
# Basic summary to support claims
df.describe()

        impressions       ctr  engagement  priority_score
count      5.000000  5.000000    5.000000        5.000000
mean    5100.000000  0.023000    0.340000     4985.500000
std     3974.921383  0.017889    0.207364     3929.795001
min      500.000000  0.005000    0.100000      497.500000
25%     2000.000000  0.010000    0.200000     1940.000000
50%     5000.000000  0.020000    0.300000     4750.000000
75%     8000.000000  0.030000    0.500000     7840.000000
max    10000.000000  0.050000    0.600000     9900.000000

## 3. Human review + the no-go list

Human Review Required

Check content accuracy before updating
Validate keyword relevance
Ensure brand tone and style
Confirm no misleading claims

No-Go (Do NOT automate)

Publishing content without human approval
Medical, legal, or sensitive topics
Deleting pages without manual review
Automatically rewriting full articles

In [9]:
# Example check: flag risky low-data rows
df["needs_review"] = df["impressions"] < 1000
df

  content_id  impressions    ctr  engagement  priority_score  needs_review
0          A        10000  0.010         0.2          9900.0         False
2          C         8000  0.020         0.5          7840.0         False
1          B         5000  0.050         0.6          4750.0         False
3          D         2000  0.030         0.3          1940.0         False
4          E          500  0.005         0.1           497.5          True

## 4. Monitoring / retrain triggers

When to Retrain or Re-evaluate

CTR drops significantly over time
Engagement rate decreases
New content types are added
Search trends change
Model performance declines on validation

In [10]:
# Simulate monitoring condition
df["ctr_drop_flag"] = df["ctr"] < 0.02
df[["content_id", "ctr", "ctr_drop_flag"]]

  content_id    ctr  ctr_drop_flag
0          A  0.010           True
2          C  0.020          False
1          B  0.050          False
3          D  0.030          False
4          E  0.005           True

## 5. Exports for the paper

Export Outputs

Ranked content action list saved for reporting
These files support the research paper and analysis

In [11]:
import os

# Create folder
os.makedirs("work/outputs", exist_ok=True)

# Save file
df.to_csv("work/outputs/content_action_queue.csv", index=False)

print("Export saved successfully!")

Export saved successfully!

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.